name: Sync Project to Roadmap
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Project Data
        uses: actions/github-script@v6
        with:
          script: |
            const query = 'query { organization(login:"printago") { projectV2(number:2) { items(first:100) { nodes { fieldValues(first:100) { nodes { __typename } } } } } } }'
            const result = await github.graphql(query)
            console.log(JSON.stringify(result, null, 2))
            require('fs').writeFileSync('./docs/debug.json', JSON.stringify(result, null, 2))
