name: Update Roadmap with Status

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual trigger

jobs:
  update-roadmap:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Fetch Issues with GraphQL
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Bearer $GH_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"query": "query { repository(owner: \"printago\", name: \"printago\") { issues(first: 100, states: OPEN) { nodes { title body url projectItems(first: 10) { nodes { project { name } column { name } } } } } } }"}' \
        https://api.github.com/graphql > issues.json

    - name: Generate Roadmap Page
      run: |
        echo "# Roadmap" > docs/roadmap.md
        echo >> docs/roadmap.md
        jq -r '.data.repository.issues.nodes[] | "## [\(.title)](\(.url))\n\n\(.body)\n\n**Project**: \(.projectItems.nodes[0].project.name // "None")\n**Status**: \(.projectItems.nodes[0].column.name // "None")\n\n---\n"' issues.json >> docs/roadmap.md

    - name: Commit and Push Updates
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add docs/roadmap.md
        git commit -m "Update roadmap with status" || echo "No changes to commit"
        git push
